server:
  port: ${APP_PORT:8080}
  servlet:
    context-path: "/security"

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_db
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
